### ISSUE TITLE
Dune exec init fails no matter the input

### ISSUE THREAD

**Issue by AoiNymph** [XiangyuShen/FFXIV-Market-Flipper#2]
The title says it all, no matter the given server name, the same error is always thrown;

**Attempted formats:**
- `dune exec -- ./src/flipper.exe init Twintania`
- `dune exec -- ./src/flipper.exe init twintania`
- `dune exec -- ./src/flipper.exe init "Twintania"`
- `dune exec -- ./src/flipper.exe init "twintania"`
- `dune exec -- ./src/flipper.exe init {Twintania}`
- `dune exec -- ./src/flipper.exe init {twintania}`
- `dune exec -- ./src/flipper.exe init {"Twintania"}`
- `dune exec -- ./src/flipper.exe init {"twintania"}`

**Response:**
> Please init with a valid server name.

**Comment by XiangyuShen** [comment]
Only the first 2 are supported, but both work fine for me.

Did you install the dependencies? It could be caused by the api call failing because you don't have the libraries.

Try running dune install.

**Comment by AoiNymph** [comment]
Rechecked everything, and the issue was indeed with a package. My **opam-version: wasn't "2.0"**, and hence threw a few deprecation errors which at a first glance I didn't notice.

**Quoted from the console:**

> `[WARNING] var was deprecated in version 2.1 of the opam CLI. Use opam var instead or set OPAMCLI environment variable to 2.0.`

After a downgrade, it seems to be working. Thanks for the swift reply and your help!
